

name: Spring Boot CI/CD Pipeline

on:
  push:
    branches: 
      - deploy-to-ec2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Verify JAR file exists
        run: ls -lh target/

      - name: Login to Docker Hub
        run: docker login -u ${{secrets.DOCKER_HUB_USERNAME}} -p ${{secrets.DOCKER_HUB_PASSWORD}}

      - name: Build Docker image
        run: docker build -t ${{secrets.DOCKER_HUB_USERNAME}}/springboot-example:latest .

      - name: Publish image to Docker Hub
        run: docker push ${{secrets.DOCKER_HUB_USERNAME}}/springboot-example:latest
      
  deploy:
    needs: build
    runs-on: aws-ec2  # Make sure this is properly set for your AWS EC2 instance

    steps:
      - name: Login to Docker Hub
        run: docker login -u ${{secrets.DOCKER_HUB_USERNAME}} -p ${{secrets.DOCKER_HUB_PASSWORD}}

      - name: Pull image from Docker Hub
        run: docker pull ${{secrets.DOCKER_HUB_USERNAME}}/springboot-example:latest

      - name: Delete old container
        run: docker rm -f springboot-example-container || true

      - name: Run Docker container
        run: docker run -d -p 8080:8080 --name springboot-example-container ${{secrets.DOCKER_HUB_USERNAME}}/springboot-example:latest
